name: fmri
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
- python>=3.6
- numpy
- scipy
- pandas
- jupyter
- scikit-learn
- matplotlib
- pytest
- scikit-image
- pymvpa
- traits
- seaborn
- statsmodels
- rpy2
- pyqt
- pip:
  - jupyterlab
  - nipype
  - nibabel
  - nilearn
  - nitime
  - nipy
  - pybids
  - dcm2bids
  - visbrain