name: fmri
dependencies:
- numpy
- scipy
- pandas
- jupyter
- scikit-learn
- matplotlib
- pytest
- scikit-image
- pip:
  - nipype
  - nibabel
  - nilearn
  - nitime
  - nipy
  - docker
  - https://github.com/kaczmarj/neurodocker/archive/master.tar.gz